server:
  port: 8080

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/collegenet_db
    url: jdbc:postgresql://ep-noisy-frost-aqijdrfv.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_w2GsdKAP1RZD
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: never
